use_frameworks!

platform :ios, '9.0'

target 'LSJHClearCache_Example' do
  pod 'LSJHClearCache', :path => '../'

  target 'LSJHClearCache_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
